### ISSUE TITLE
bug report: non-zero error code should surface up to runtime

### ISSUE THREAD

**Issue by SongGithub** [MYOB-Technology/kt#2]
## scenario: 
It is known that if we want to update labels on daemonset, we will have an error ```The DaemonSet "kube2iam" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"kube2iam", "repo":"ops-kube-system"}: `selector` does not match template `labels````. However, kt doesn't allow the error code to surface up to run-time, such as CI agent running it to alert us about the error. 

## diagonosis
I have managed to reproduce the error by manually ensure label in spec.template.metadata.labels has different labels to the input ones. As a result, I have error ```The DaemonSet "kube2iam" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"kube2iam", "repo":"ops-kube-system"}: `selector` does not match template `labels```. When I check error code `echo $*`, it is 1. However, if I ran it in `$dcr kt deploy -e "$env" && echo $?` fashion, error code returned is 0, which is incorrect.

**Comment by pvdvreede** [comment]
This should be fixed in 0.2.3 by 8df62479e80e936e56704ad2460f155b57c79d3b
